//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitinolProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetalQualityBaseValue
    {
        public int MetalQualityBaseValuesId { get; set; }
        public int MetalId { get; set; }
        public int LoadingSpeed { get; set; }
        public int LateralShearRate { get; set; }
        public int LongitudinalShearRate { get; set; }
        public decimal ShearStrainRate { get; set; }
        public int SpallStrength { get; set; }
    
        public virtual Metal Metal { get; set; }
    }
}
