//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitinolProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metal
    {
        public Metal()
        {
            this.MetalQualityBaseValues = new HashSet<MetalQualityBaseValue>();
            this.MetalSamples = new HashSet<MetalSample>();
        }
    
        public int MetalId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MetalQualityBaseValue> MetalQualityBaseValues { get; set; }
        public virtual ICollection<MetalSample> MetalSamples { get; set; }
    }
}
