//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitinolProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NicelideTitanumCoefficientWeighting
    {
        public decimal SampleThickness { get; set; }
        public decimal HammerThickness { get; set; }
        public decimal HammerSpeed { get; set; }
        public decimal SpallSpeed { get; set; }
        public decimal SpallStrength { get; set; }
    }
}
